final doctorMapList = [
  {
    "name": "Dr. David Kemp",
    "type": "Heart Sergeon",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/doctor.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. katthy Mathews",
    "type": "Neurology",
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/doctor_4.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "DR. Morris",
    "type": "Cardio Sergeon",
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image":"assets/doctor_3.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Bruce Banner",
    "type": "Heart Sergeon",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image":"assets/doctor_1.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  }
];
